import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AuthProvider from './AuthProvider'
import Topbar from '../components/shared/Topbar' 
import SideNavigation from '../components/shared/SideNavigation'
import RightSidebar from '../components/shared/RightSidebar'
import Bottombar from '../components/shared/Bottombar'

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>

        <section className='relative bg-black flex max-w-[1300px]'>
            <Topbar/>
            <main className='flex h-screen w-screen bg-red-400'>
              <SideNavigation/>
              {children}
              <RightSidebar/>
            </main>
            <Bottombar/>
        </section>
        </AuthProvider>
      </body>
    </html>
  )
}
